global using System.Collections;
global using System.ComponentModel;
global using System.Data;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.IO.Compression;
global using System.Reflection;
global using System.Runtime.InteropServices;
global using System.Runtime.Serialization;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Nodes;
global using System.Text.Json.Serialization;
global using System.Xml;

global using Box.Coroutines;
global using Box.Entities;
global using Box.Entities.Container;
global using Box.Entities.Graphics;
global using Box.Enums;
global using Box.Graphics;
global using Box.Graphics.Fonts;
global using Box.Helpers;
global using Box.Inputs;
global using Box.Inputs.InputStates;
global using Box.Interfaces;
global using Box.Loaders.Maps.Data;
global using Box.Loaders.Maps.Layers;
global using Box.Loaders.Maps.Settings;
global using Box.Loaders.Spritesheets;
global using Box.Screens;
global using Box.Signals;
global using Box.Sounds;
global using Box.Systems;
global using Box.Utils;

global using BoxPackLib;
global using BoxPackLib.BoxPackFiles;

global using BmFont = Box.Loaders.BitmapFonts.BitmapFont;
global using BmFontLoader = Box.Loaders.BitmapFonts.BitmapFontLoader;
global using BoxColor = Box.Graphics.Color;
global using BoxFont = Box.Graphics.Fonts.Font;
global using BoxRenderTarget = Box.Entities.Graphics.RenderTarget;
global using SFMLAxis = SFML.Window.Joystick.Axis;
global using SFMLBlendMode = SFML.Graphics.BlendMode;
global using SFMLClock = SFML.System.Clock;
global using SFMLColor = SFML.Graphics.Color;
global using SFMLContextSettings = SFML.Window.ContextSettings;
global using SFMLFloatRect = SFML.Graphics.FloatRect;
global using SFMLFont = SFML.Graphics.Font;
global using SFMLGamepad = SFML.Window.Joystick;
global using SFMLGlyph = SFML.Graphics.Glyph;
global using SFMLImage = SFML.Graphics.Image;
global using SFMLKeyboard = SFML.Window.Keyboard;
global using SFMLMouse = SFML.Window.Mouse;
global using SFMLPrimitiveType = SFML.Graphics.PrimitiveType;
global using SFMLRectF = SFML.Graphics.FloatRect;
global using SFMLRectI = SFML.Graphics.IntRect;
global using SFMLRenderStates = SFML.Graphics.RenderStates;
global using SFMLRenderTexture = SFML.Graphics.RenderTexture;
global using SFMLRenderWindow = SFML.Graphics.RenderWindow;
global using SFMLSoundBuffer = SFML.Audio.SoundBuffer;
global using SFMLSoundInstance = SFML.Audio.Sound;
global using SFMLSoundStatus = SFML.Audio.SoundStatus;
global using SFMLSprite = SFML.Graphics.Sprite;
global using SFMLStyles = SFML.Window.Styles;
global using SFMLTexture = SFML.Graphics.Texture;
global using SFMLTime = SFML.System.Time;
global using SFMLTransform = SFML.Graphics.Transform;
global using SFMLVectF = SFML.System.Vector2f;
global using SFMLVector = SFML.System.Vector2f;
global using SFMLVector3f = SFML.System.Vector3f;
global using SFMLVectorF = SFML.System.Vector2f;
global using SFMLVectorI = SFML.System.Vector2i;
global using SFMLVectorU = SFML.System.Vector2u;
global using SFMLVertex = SFML.Graphics.Vertex;
global using SFMLVertexBuffer = SFML.Graphics.VertexBuffer;
global using SFMLVideoMode = SFML.Window.VideoMode;
global using SFMLView = SFML.Graphics.View;
